### ISSUE TITLE
大屏预览展示逻辑

### ISSUE THREAD

**Issue by YLQZ** [Aaron52077/react-visual-data#1]
预览时 非全屏 取 宽比高比中的最小值，F11 全屏时 重新计算获取比例，任意取一值(建议用宽比)（因为在完全全屏时，宽高比一致），退出全屏 重新计算 并取最小值，
实现方式建议：先阻止F11 原事件，并调用 screenfull 插件的 toggle()，onfullscreenchange 事件 重置计算比例

**Comment by Aaron52077** [comment]
> 预览时 非全屏 取 宽比高比中的最小值，F11 全屏时 重新计算获取比例，任意取一值(建议用宽比)（因为在完全全屏时，宽高比一致），退出全屏 重新计算 并取最小值，
> 实现方式建议：先阻止F11 原事件，并调用 screenfull 插件的 toggle()，onfullscreenchange 事件 重置计算比例

谢谢建议，目前在开发vue3版本，后续会修复此bug

**Comment by Aaron52077** [comment]
已修复
