### ISSUE TITLE
功能bug

### ISSUE THREAD

**Issue by ArcherTrister** [Aaron52077/react-visual-data#3]
bug1：点击左侧大屏设计器其中一个图层，修改其中一个属性之后再点击另一个图层修改属性，比如修改width属性，功能正常，
但是如果点击中间画布上的其中一个图层修改width属性，再切换另一个图层，只要修改的第一个图层的input框不失去焦点，第二个图层渲染出来的width属性是刚刚修改的数值

bug2：选择屏幕大小之后，画布改变了，画布上的图层没有自适应

**Comment by Aaron52077** [comment]
> bug1：点击左侧大屏设计器其中一个图层，修改其中一个属性之后再点击另一个图层修改属性，比如修改width属性，功能正常，
> 但是如果点击中间画布上的其中一个图层修改width属性，再切换另一个图层，只要修改的第一个图层的input框不失去焦点，第二个图层渲染出来的width属性是刚刚修改的数值
> 
> bug2：选择屏幕大小之后，画布改变了，画布上的图层没有自适应

已修复bug1，针对bug2，这个设计是针对设计预览后的屏幕大小，因此在设计模式下不会有所关联

**Comment by ArcherTrister** [comment]
那如果这样的话，在设计的时候就必须想好最终预览的画布大小才能避免了，但是很多需求是不确定，假如刚开始选择了一个画布，后面需求变了画布需要变大或变小，那之前所有的图层就必须重新布局，在改变画布的时候我尝试使用setview来实现，但是效果不是太好，希望有更好的解决办法。非常感谢！

**Comment by Aaron52077** [comment]
> 那如果这样的话，在设计的时候就必须想好最终预览的画布大小才能避免了，但是很多需求是不确定，假如刚开始选择了一个画布，后面需求变了画布需要变大或变小，那之前所有的图层就必须重新布局，在改变画布的时候我尝试使用setview来实现，但是效果不是太好，希望有更好的解决办法。非常感谢！

首先，设计画布变大变小不影响最终预览效果，其中用户可以自定义页面大小再来设计大屏。如果设计好的大屏去改变页面大小位置是不会受影响的，预览显示预设的页面大小

**Comment by Aaron52077** [comment]
fix
