### ISSUE TITLE
大佬问一下  react-mat-pro 项目地址在哪里

### ISSUE THREAD

**Issue by erlei22** [Aaron52077/react-visual-data#9]
最近正在做react keepAlive 所以想观摩一下怎么做的

**Comment by Aaron52077** [comment]
> 最近正在做react keepAlive 所以想观摩一下怎么做的

借助第三方库react-activation呢

**Comment by Aaron52077** [comment]
> 最近正在做react keepAlive 所以想观摩一下怎么做的

https://gitee.com/wuli-admin/angular-mat-pro/tree/react18/
